services:
  db:
    image: postgres:14-alpine
    container_name: apartman-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=apartman_db
    # command: ... SATIRINI TAMAMEN SİLİN
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # ./init-scripts:... SATIRINI DA ŞİMDİLİK SİLİN VEYA YORUM SATIRI YAPIN (# koyarak)

  backend:
    build: ./backend
    container_name: apartman-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/apartman_db
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: apartman-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  postgres_data: